#!/usr/bin/env python

from __future__ import print_function
import sh, sys, os, re

# for 7.4
VIM_README_URL = 'ftp://ftp.vim.org/pub/vim/patches/7.4/README'
TWITTER_OAUTH_FILE = 'twitter_oauth'
LATEST_PATCH_FILE = 'latest_patch'

def err(*obj):
    #print('ERR: ', *obj, file=sys.stderr)
    print('ERROR: ', *obj)

if not os.path.isfile(TWITTER_OAUTH_FILE):
    err("""
    No twitter oauth file found. It can be generated by twitter command
    line tool automatically. Just rename it to %s and put it here.
    """ % TWITTER_OAUTH_FILE)
    sys.exit(0)

latest_patch = ''

with open(LATEST_PATCH_FILE) as f:
    latest_patch = f.readline()

try:
    #requests doesn't yet support ftp and i don't want monkey patching. so cURL.
    last_line = sh.curl(VIM_README_URL, '-s').stdout.strip().split('\n')[-1].strip()
except Exception as e:
    err("Can not get the last line of %s, reason: %s" % (VIM_README_URL, e))
    sys.exit(1)

words = last_line.split()

version_number = words[1]
if not re.search('^\d\.\d\.\d{3}$', version_number):
    err("%s looks unlike a version number" % version_number)
    sys.exit(1)

if version_number == latest_patch:
    #print("no updates")
    sys.exit(0)

tweet_text = '#vim new patch: ' + ' '.join(words[1:])[:140]
try:
    sh.twitter('--oauth', TWITTER_OAUTH_FILE, 'set', tweet_text)
    with open(LATEST_PATCH_FILE, 'w') as f:
        f.write(version_number)
except Exception as e:
    err("Failed to tweet %s, reason: %s" % (tweet_text, e))

